### PR TITLE
Fix not passing request headers to client

### LINKED ISSUE #8: No longer possible to pass headers?
Seems that ability was removed here? https://github.com/phergie/plugin-http/commit/ffd2b6c60d923300227e4f4f2611e001cbe4212d#diff-f7fcf01b75ab0236c970de527853c3abL106

Or am I being dumb per usual? 😁

### PR DESCRIPTION
**Pull request by WyriHaximus**
Fixes #8

### CODE REVIEW

**Comment by sitedyno** [comment]
Do the headers need to be added to makeStreamingHttpRequest() as well?

**Comment by WyriHaximus** [comment]
Yup you're right

**Comment by matthewtrask** [comment]
@WyriHaximus is this all good?

**Comment by WyriHaximus** [comment]
@matthewtrask looks like it but I would like to add tests for it before merging tbh

**Comment by WyriHaximus** [comment]
Thanks to @sitedyno for the tests, will merge this PR shortly

**Comment by WyriHaximus** [comment]
@sitedyno just tagged [`4.1.0`](https://github.com/phergie/plugin-http/releases/tag/4.1.0) with this and your PR in it

**Comment by sitedyno** [comment]
Thanks! 💃

**Pull request merged**
